#!/usr/bin/env python3
"""
import_grades.py
---------------
Reads a grade-report DOCX (generated by AI Grader), extracts every student's
roll number and scores, then writes them into the matching rows of an Excel
roster file.

Requirements:
    pip install python-docx openpyxl

Usage:
    python import_grades.py <report.docx> <roster.xlsx> --mark-col C [options]

Column arguments accept Excel letters (A, B, C, AA …) or 1-based numbers (1, 2, 3 …).

Examples:
    # Write scores into column C, roll numbers are in column A (default)
    python import_grades.py GradeReport.docx Roster.xlsx --mark-col C

    # Also fill grade (D) and percentage (E), roll numbers in column B
    python import_grades.py GradeReport.docx Roster.xlsx --roll-col B --mark-col C --grade-col D --pct-col E

    # Save to a specific output file
    python import_grades.py GradeReport.docx Roster.xlsx --mark-col C --output Results.xlsx
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Optional

# ── Dependency check ───────────────────────────────────────────────────────────
try:
    from docx import Document
except ImportError:
    sys.exit(
        "Missing dependency: python-docx\n"
        "Install with:  pip install python-docx"
    )

try:
    import openpyxl
except ImportError:
    sys.exit(
        "Missing dependency: openpyxl\n"
        "Install with:  pip install openpyxl"
    )


# ── Column-letter / 1-based-number → 0-based index ────────────────────────────
def col_to_index(col: str) -> int:
    """
    "A"  → 0,  "B" → 1,  "C" → 2,  "AA" → 26
    "1"  → 0,  "2" → 1,  "3" → 2   (1-based numeric strings)
    """
    s = str(col).strip().upper()
    if not s:
        raise ValueError("Column must not be empty.")
    if s.isdigit():
        return max(0, int(s) - 1)
    idx = 0
    for ch in s:
        if not ch.isalpha():
            raise ValueError(f"Invalid column specifier: {col!r}")
        idx = idx * 26 + (ord(ch) - ord("A") + 1)
    return idx - 1


# ── Parse the grade-report DOCX ────────────────────────────────────────────────
# Report structure (generated by generateReport.js):
#   Heading 1  → student roll number / name
#   Paragraph  → "Score: 45 / 80  |  Percentage: 56.3%  |  Grade: C"
#   Table      → per-criterion breakdown  (not needed here)

SCORE_RE = re.compile(
    r"Score:\s*([\d.]+)\s*/\s*([\d.]+)"
    r"\s*\|\s*Percentage:\s*([\d.]+)%"
    r"\s*\|\s*Grade:\s*([A-F])",
    re.IGNORECASE,
)

# Heading style names produced by different docx generators:
#   Word / python-docx  → "Heading 1"
#   npm docx package    → style id "Heading1" which python-docx may surface as "Heading1"
def _is_heading1(style_name: str) -> bool:
    n = (style_name or "").lower().replace(" ", "")
    return n in ("heading1",)


def parse_report(docx_path: str) -> dict:
    """
    Returns:
        {
          "ROLL001": {"total": 45.0, "max": 80.0, "pct": 56.3, "grade": "C"},
          ...
        }
    Roll numbers are stored upper-cased for case-insensitive matching.

    Strategy (two-pass, style-independent):
      Pass 1 – try heading-style detection.
      Pass 2 – fallback: for every score line, treat the immediately preceding
               non-empty paragraph as the student name. This works even when the
               docx generator omits proper heading styles.
    """
    doc = Document(docx_path)
    students: dict = {}

    # Collect all non-empty paragraph texts with their styles
    paras = [
        (p.text.strip(), p.style.name if p.style else "")
        for p in doc.paragraphs
        if p.text.strip()
    ]

    # ── Pass 1: heading-style detection ───────────────────────────────────────
    current_name: Optional[str] = None
    for text, style in paras:
        if _is_heading1(style):
            current_name = text.upper()
            continue
        m = SCORE_RE.search(text)
        if m and current_name:
            students[current_name] = {
                "total": float(m.group(1)),
                "max":   float(m.group(2)),
                "pct":   float(m.group(3)),
                "grade": m.group(4).upper(),
            }
            current_name = None

    # ── Pass 2 fallback: use the paragraph *before* each score line ────────────
    # Only runs if pass 1 found nothing (heading styles weren't recognised).
    if not students:
        texts = [t for t, _ in paras]
        for i, text in enumerate(texts):
            m = SCORE_RE.search(text)
            if not m or i == 0:
                continue
            candidate = texts[i - 1]
            # Skip if the previous line itself looks like a score/header line
            if SCORE_RE.search(candidate):
                continue
            students[candidate.upper()] = {
                "total": float(m.group(1)),
                "max":   float(m.group(2)),
                "pct":   float(m.group(3)),
                "grade": m.group(4).upper(),
            }

    return students


# ── Update the Excel roster ────────────────────────────────────────────────────
def update_roster(
    roster_path: str,
    students:    dict,
    roll_col:    int,
    mark_col:    int,
    grade_col:   Optional[int],
    pct_col:     Optional[int],
    output_path: str,
    sheet:       str,           # sheet name or 0-based index as string
) -> tuple:
    """
    Iterates every row in the worksheet, looks up the roll number in `students`,
    and writes score / grade / percentage into the requested columns.

    Matching order:
      1. Exact match (both sides uppercased + stripped).
      2. The Excel roll number appears as a substring of the report student name
         (handles filenames like "24F-5005 Assignment Submission").
      3. A report student name starts with the Excel roll number.

    Returns (matched_count, not_found_list).
    """
    wb = openpyxl.load_workbook(roster_path)

    # Select sheet
    if sheet.isdigit():
        ws = wb.worksheets[int(sheet)]
    else:
        ws = wb[sheet]

    # Pre-build a list of (report_key_upper, student_data) for substring scanning
    report_items = [(k.upper(), v) for k, v in students.items()]

    def normalize(s: str) -> str:
        """Strip spaces, hyphens, underscores, dots → pure alphanumeric for fuzzy compare."""
        return re.sub(r"[\s\-_.]", "", s).upper()

    # Pre-build normalized index for O(1) normalized lookups
    normalized_index: dict = {}
    for rk, rv in report_items:
        nk = normalize(rk)
        normalized_index.setdefault(nk, rv)  # first occurrence wins

    def find_student(roll_no: str):
        """Return student data for roll_no, or None if not found."""
        key = roll_no.upper()
        # 1. Exact match
        if key in students:
            return students[key]
        # 2. Normalized match — ignores hyphens/spaces/dots
        #    e.g. "24F-5005" == "24F5005", "25F-5500" == "25F 5500"
        nkey = normalize(key)
        if nkey in normalized_index:
            return normalized_index[nkey]
        # 3. Excel roll number is a substring of a report name
        #    e.g. Excel="24F-5005", Report="24F-5005 JOHN ASSIGNMENT"
        for rk, rv in report_items:
            if key in rk:
                return rv
        # 4. Normalized Excel roll is a prefix of a normalized report name
        for rk, rv in report_items:
            if normalize(rk).startswith(nkey):
                return rv
        return None

    matched   = 0
    not_found = []
    used_keys: set = set()   # report keys that were actually matched

    for row in ws.iter_rows():
        if roll_col >= len(row):
            continue
        roll_cell = row[roll_col]
        roll_no   = str(roll_cell.value or "").strip().upper()

        if not roll_no:
            continue

        s = find_student(roll_no)
        if s is None:
            not_found.append(roll_no)
            continue

        r = roll_cell.row                                           # 1-based row number

        ws.cell(row=r, column=mark_col + 1, value=s["total"])     # openpyxl is 1-based

        if grade_col is not None:
            ws.cell(row=r, column=grade_col + 1, value=s["grade"])

        if pct_col is not None:
            ws.cell(row=r, column=pct_col + 1, value=s["pct"])

        matched += 1
        # Track which report key was consumed (for the diagnostic below)
        for rk, rv in report_items:
            if rv is s:
                used_keys.add(rk)
                break

    wb.save(output_path)

    # Report keys that were never matched to any Excel row
    unused_keys = [rk for rk, _ in report_items if rk not in used_keys]
    return matched, not_found, unused_keys


# ── CLI ────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="Import AI Grader scores from a DOCX report into an Excel roster.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("report",
        help="Path to the grade-report DOCX generated by AI Grader")
    parser.add_argument("roster",
        help="Path to the student roster Excel file (.xlsx)")

    parser.add_argument("--roll-col",  default="A",
        help="Column in roster that contains roll numbers (default: A)")
    parser.add_argument("--mark-col",  required=True,
        help="Column to write total scores into (e.g. C)")
    parser.add_argument("--grade-col", default=None,
        help="Column to write letter grades (A/B/C/D/F) — optional")
    parser.add_argument("--pct-col",   default=None,
        help="Column to write percentage marks — optional")
    parser.add_argument("--output",    default=None,
        help="Output file path (default: updated-<roster-name>.xlsx)")
    parser.add_argument("--sheet",     default="0",
        help="Sheet index (0-based) or sheet name (default: 0 = first sheet)")

    args = parser.parse_args()

    # ── Validate paths ─────────────────────────────────────────────────────────
    report_path = Path(args.report)
    roster_path = Path(args.roster)

    if not report_path.is_file():
        sys.exit(f"Error: report file not found — {report_path}")
    if not roster_path.is_file():
        sys.exit(f"Error: roster file not found — {roster_path}")

    # ── Resolve column indices ─────────────────────────────────────────────────
    try:
        roll_col  = col_to_index(args.roll_col)
        mark_col  = col_to_index(args.mark_col)
        grade_col = col_to_index(args.grade_col) if args.grade_col else None
        pct_col   = col_to_index(args.pct_col)   if args.pct_col   else None
    except ValueError as exc:
        sys.exit(f"Column error: {exc}")

    # ── Default output path ────────────────────────────────────────────────────
    if args.output:
        output_path = Path(args.output)
    else:
        output_path = roster_path.parent / f"updated-{roster_path.name}"

    # ── Parse the grade report ─────────────────────────────────────────────────
    print(f"\nParsing grade report:  {report_path}")
    try:
        students = parse_report(str(report_path))
    except Exception as exc:
        sys.exit(f"Failed to read report: {exc}")

    if not students:
        sys.exit(
            "No student grades found in the report.\n"
            "Make sure the file is a grade report generated by AI Grader."
        )

    print(f"  {len(students)} student(s) found in report:")
    for roll, s in students.items():
        print(f"    {roll[:50]:50s}  {s['total']}/{s['max']}  {s['grade']}")

    # ── Update the roster ──────────────────────────────────────────────────────
    print(f"\nUpdating roster:       {roster_path}")
    try:
        matched, not_found, unused_keys = update_roster(
            str(roster_path), students,
            roll_col, mark_col, grade_col, pct_col,
            str(output_path), args.sheet,
        )
    except Exception as exc:
        sys.exit(f"Failed to update roster: {exc}")

    print(f"  {matched}/{len(students)} student(s) matched and filled.")

    if not_found:
        # Filter out likely header rows (purely alphabetic labels like "Roll No", "Name")
        real_not_found = [r for r in not_found if any(ch.isdigit() for ch in r)]
        if real_not_found:
            preview = real_not_found[:10]
            extra   = len(real_not_found) - 10
            print(
                f"\n  [Excel → not in report] These roll numbers had no match:\n"
                + "\n".join(f"    {r}" for r in real_not_found[:20])
                + (f"\n    … and {len(real_not_found) - 20} more" if len(real_not_found) > 20 else "")
            )

    if unused_keys:
        print(
            f"\n  [Report → not in Excel] These report entries were never matched:\n"
            + "\n".join(f"    {k}" for k in unused_keys[:20])
            + (f"\n    … and {len(unused_keys) - 20} more" if len(unused_keys) > 20 else "")
        )
        print("  ↑ Compare these with the unmatched Excel roll numbers above to spot typos/format differences.")

    print(f"\nSaved:  {output_path}\n")


if __name__ == "__main__":
    main()
